language: python
python:
#  - "2.6" # No OrderedDict
  - "2.7"
#  - "3.2" # unicode prefix u"" not supported
  - "3.3"
  - "3.4"
  - "3.5"
install:
- pip install -r requirements.txt
- pip install coveralls
script: coverage run --source yamlns ./setup.py test
after_success:
- coveralls

