language: python
python:
#  - "2.6" # No OrderedDict
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
- python setup.py develop
- pip install pytest
- pip install coveralls
script:
- coverage run --source yamlns -m py.test -v
after_success:
- coveralls

