language: python
python:
#  - "2.6" # No OrderedDict
  - "2.7"
#  - "3.2" # unicode prefix u"" not supported
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.8"
install:
- pip install -r requirements.txt
- pip install pytest
- pip install coveralls
script:
- coverage run --source yamlns pytest -v
after_success:
- coveralls

